version: '3.8'

services:
  db:
    image: postgres:15
    container_name: quiz_postgres
    restart: always
    environment:
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: quiz_django
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=quizdb
      - DB_USER=quizuser
      - DB_PASSWORD=quizpass
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
