# Generated by Django 5.2.6 on 2025-09-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('quiz', 'Quiz classico'), ('anagram', 'Anagramma'), ('truefalse', 'Vero/Falso')], default='quiz', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
